language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database testing;'
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

script: phpunit